output:
  # Make output more digestible with quickfix in vim/emacs/etc.
  sort-results: true
  print-issued-lines: false

linters:
  enable:
    - nolintlint
    - revive
    - staticcheck
    - asasalint
    - bodyclose
    - contextcheck
    - cyclop
    - dupword
    - errname
    - exhaustive
    - loggercheck
    - misspell
    - nestif
    - perfsprint
    - prealloc
    - predeclared
    - testifylint
    - unconvert
    - usestdlibvars
    - wsl

linters-settings:
  govet:
    # These govet checks are disabled by default, but they're useful.
    enable:
      - niliness
      - reflectvaluecompare
      - sortslice
      - unusedwrite
      - defers
      - atomic
      - nilfunc
      - printf
      - sortslice
      - tests
