telemetry:
  logging:
    level: debug  # debug, info, warn, error, fatal
    encoding: console

#api:
#  http:
#    ...

routers:
  language:
    - id: myrouter
      models:
        - id: openai
          openai:
            api_key: "${env:OPENAI_API_KEY}"
