name: release

on:
  push:
    tags:
      - "*"
# TODO: uncomment the lines below after tests
#    branches:
#      - main

permissions:
  contents: write
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  vuln:
    uses: ./.github/workflows/vuln.yaml
  release:
    needs: [lint, vuln]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
