name: release

on:
  push:
    tags:
      - "*"
# TODO: uncomment the lines below after tests
#    branches:
#      - main

permissions:
  contents: write
  packages: write

jobs:
# TODO: uncomment after tests
#  lint:
#    uses: ./.github/workflows/lint.yaml
#  vuln:
#    uses: ./.github/workflows/vuln.yaml
  release:
#    needs:
#      - lint
#      - vuln
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v5
#        with:
#          distribution: goreleaser
#          version: latest
#          args: release --clean
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  images:
    strategy:
      matrix:
        image:
          - alpine
          - ubuntu
          - distroless
          - redhat
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
# TODO: uncomment after tests
#      - name: login into Github Container Registry
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: go to images
        run: cd images

      - name: build ${{ matrix.image }} image
        run: VERSION=${{ github.ref_name }} COMMIT=$(git rev-parse --short "$GITHUB_SHA") BUILD_DATE="$(date --rfc-3339=date)" make ${{ matrix.image }}

      - name: publish ${{ matrix.image }} image to Github Container Registry
        run: VERSION=${{ github.ref_name }} make publish-ghcr-${{ matrix.image }}
